### ISSUE TITLE
Update-xDSCResource adds an extra newline at the end of each *-TargetResource function

### ISSUE THREAD

**Issue by SimonWahlin** [PowerShell/xDSCResourceDesigner#11]
Every time I run Update-xDSCResource a new blank line is added just before the closing '}' on each *-TargetResource function.

The helper functions are not affected.

**Comment by tysonjhayes** [comment]
Is this fixed? If so can we close this issue?

**Comment by SimonWahlin** [comment]
Yes it is fixed, I'll close this.
