### ISSUE TITLE
Update-xDscResource and New-xDscResource does not use UTF-8 encoding

### ISSUE THREAD

**Issue by SimonWahlin** [PowerShell/xDSCResourceDesigner#22]
According to tests in https://github.com/PowerShell/DscResource.Tests files should use UTF-8 instead of Unicode.

Each time Update-DSCResource is run, it encode files with unicode, making the tests fail.

**Comment by SimonWahlin** [comment]
I just realized that mofcomp wont accept the schema file in UTF-8 encoding. 

I guess I'll have to get used to run ConvertTo-UTF8 before commit. 

Should I close this issue?

**Comment by KarolKaczmarek** [comment]
yes, unfortunately you will need to convert to UTF8 manually before committing
