### ISSUE TITLE
Change Parameter formatting to match new StyleGuidelines.md

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xDSCResourceDesigner#50]
See this issue:
https://github.com/PowerShell/DscResources/issues/121

Formatting needs to be changed to:
[Type] $Name = 'value'

Current formatting is:
[Type]
$Name = 'value'

**Comment by kwirkykat** [comment]
Current formatting is correct per the new [style guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameter-type-on-line-above)
