### ISSUE TITLE
Commands from this module doesn't work with WMF 5 April preview

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/xDSCResourceDesigner#6]
Due to bug reported at connect: https://connect.microsoft.com/PowerShell/feedback/details/1280407, commands from this module throw *Unable to find type [DscResourceProperty]* error

**Comment by GoateePFE** [comment]
Also, the ValidateSet parameter is now changed to ValueMap. This is not documented in the documented examples, version history, or the comment-based help. What is the new proper syntax?

**Comment by dlwyatt** [comment]
Fixed with PRs #5 and #7 , respectively.
