### ISSUE TITLE
Question about resource attribute

### ISSUE THREAD

**Issue by jdhitsolutions** [PowerShell/xDSCResourceDesigner#63]
Since the help documentation is a bit light I thought I'd ask here. In New-xDSCResourceProperty the Attribute property is required. I understand the Key and Required values. But am not sure what Read or Write is referring to. The resources I've test built seem to work just fine when using Write. I assumed this meant "writing" to the something on the computer. But that's just an assumption on my part. I'd appreciate any clarification on the Read and Write parameter values for Attribute.

**Comment by adamrushuk** [comment]
I found this when wanting the same clarification myself: 

The `[write]` qualifier indicates that this property is optional when using the custom resource in a configuration script. The `[read]` qualifier indicates that a property cannot be set by a configuration, and is for reporting purposes only.`

Source: https://docs.microsoft.com/en-us/powershell/dsc/authoringresourcemof

**Comment by jdhitsolutions** [comment]
Thanks. I guess I wasn't that far off in my assumption.

**Comment by adamrushuk** [comment]
No worries Jeff. Glad to repay a simple link, after the many years I've spent learning from your content! :)
