### ISSUE TITLE
Test-MockSchema reports that a DSC resource doesnt match the class name when there are two classes

### ISSUE THREAD

**Issue by mcollera** [PowerShell/xDSCResourceDesigner#73]
When you have a custom embeded class in the schema mof Test-MockSchema only grabs the last class to test if names match. This reports an error when the names do match.

Example
[ClassVersion("1.0.0.0"), FriendlyName("EmbededClass")]
class EmbededClass: OMI_BaseResource
{
    [Key] String Name;
    [Write, EmbeddedInstance("SubClass")] string SubClass[];
};

[ClassVersion("1.0.0.0")]
class SubClass{
    [Write] String Param1;
    [Write] String Param2;
};

**Comment by johlju** [comment]
Labeled as bug and help wanted so anyone in the community can run with it.

As a workaround the instance that are named as the file should be last in the file.
Assuming the filename is `JL_Embedded.schema.mof` (where JL is the prefix, in this case my JL is my initials)
```
[ClassVersion("1.0.0.0")]
class SubClass{
    [Write] String Param1;
    [Write] String Param2;
};

[ClassVersion("1.0.0.0"), FriendlyName("Embedded")]
class JL_Embedded: OMI_BaseResource
{
    [Key] String Name;
    [Write, EmbeddedInstance("SubClass")] string SubClass[];
};
```

**Comment by mcollera** [comment]
@johlju Agreed moving the class to the bottom is a workaround but then that breaks psscriptanalyzer rule 'psdscuseidenticalmandatoryparametersfordsc'. Returning error Invoke-ScriptAnalyzer : Object reference not set to an instance of an object.
